# Generated by Django 5.2.1 on 2025-06-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmaterial',
            name='unit_system',
            field=models.CharField(choices=[('imperial', 'Imperial'), ('metric', 'Metric')], default='metric', max_length=10),
        ),
    ]
