# Generated by Django 5.2.1 on 2025-06-03 09:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('partname', models.CharField(db_index=True, max_length=200)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('width', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('thickness', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('material', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('angle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orientation', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='projects.project')),
            ],
            options={
                'ordering': ['partname'],
            },
        ),
        migrations.CreateModel(
            name='PartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(max_length=20)),
                ('changes', models.JSONField(default=dict)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='parts.part')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('thickness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('material', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['project', 'partname'], name='parts_part_project_e0445f_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['material'], name='parts_part_materia_6cb38e_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['category'], name='parts_part_categor_bac559_idx'),
        ),
    ]
