# Generated by Django 5.2.1 on 2025-06-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=4, max_digits=10)),
                ('width', models.DecimalField(decimal_places=4, max_digits=10)),
                ('thickness', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.stockmaterial')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='projects.project')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
