# Generated by Django 5.2.1 on 2025-06-03 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cutlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutlists', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='CutlistPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('thickness', models.FloatField()),
                ('material', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('cutlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cutlists.cutlist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CutlistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('thickness', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cutlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_materials', to='cutlists.cutlist')),
            ],
        ),
    ]
