# Generated by Django 5.2.1 on 2025-06-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlists', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutlistpart',
            options={'ordering': ['partname']},
        ),
        migrations.RenameField(
            model_name='cutlistpart',
            old_name='name',
            new_name='partname',
        ),
        migrations.AddField(
            model_name='cutlistpart',
            name='angle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cutlistpart',
            name='orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='length',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.stockmaterial'),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='thickness',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='width',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='length',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='thickness',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='width',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
