# Generated by Django 5.2.1 on 2025-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutlists', '0002_alter_cutlistpart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutlistpart',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutlistpart',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='thickness',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cutliststock',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
